### PR TITLE
Added support for JPEG images in PDF export.

### PR DESCRIPTION
**Pull request by trueg**
This results in much much much smaller files while keeping the image
quality high (One could even add the image quality as a configuration
parameter. For now it is fixed at 1.0.)

For me this means 8mb instructions instead of 400mb ones!

### CODE REVIEW

**Comment by trueg** [comment]
png uses so much more space because it is lossless while jpeg is much more heavily compressed. I will make the requested changes ASAP.

**Comment by Leowolf27** [comment]
The png format yields a cleaner sharper image, while the jpeg, regardless of the quality introduces compression artifacts, especially on red colored areas. If you were to add a jpeg export options, please do allow both png and jpeg. The fact is that png can be manipulated further without quality loss, especially the hi-res exports that help in creating very professional looking instructions. The same cannot be said for jpeg, which may degrade even more with every manipulation.

**Comment by trueg** [comment]
@remig If you are concerned about users being confused by the choice I see other possibilities:
1. An advanced section in the dialog or
2. instead of a dropdown have a checkbox which says something like "optimize for print" which would enable png.

**Comment by remig** [comment]
> I may have been mistaken as you are proposing the change to PDF export and I was thinking about the actual individual image export.

Right; we are only changing the images embedded inside PDFs, we are not changing the Export PNG Images option. PDFs are usually not edited, they are printed / shared as is.

I compared several PDFs rendered with JPEG vs PNG; they are basically indistinguishable, both on monitors and printed, and at any DPI setting. Because of that, I'm comfortable making the switch to JPEG inside PDFs, with no option to choose.

This change also makes a noticeable difference in performance during PDF export. These new PDFs are up to 50x smaller, which means the same machine can now render 50x more content before running out of memory and crashing (which happens more often than I'd like).

**Pull request merged**
